#pragma once

#define BOTTOM_SCREEN_WIDTH		320
#define BOTTOM_SCREEN_HEIGHT	240

#define TOP_SCREEN_WIDTH        400
#define TOP_SCREEN_HEIGHT       BOTTOM_SCREEN_HEIGHT

#define TOP_WIDTH_CENTER		TOP_SCREEN_WIDTH  / 2
#define TOP_HEIGHT_CENTER		TOP_SCREEN_HEIGHT / 2

#define BOTTOM_WIDTH_CENTER		BOTTOM_SCREEN_WIDTH  / 2
#define BOTTOM_HEIGHT_CENTER	BOTTOM_SCREEN_HEIGHT / 2

#define LOWEST_SCREEN_POSITION  0

#define GREEN 	C2D_Color32(0, 255, 0, 255)
#define YELLOW 	C2D_Color32(255, 255, 0, 255)
#define RED 	C2D_Color32(255, 0, 0, 255)
